import { EventInfoType } from "../_types";

export type ArtistType = {
  name: string;
  group?: string[];
  profileImage: string;
};

export const MOCK: ArtistType[] = [
  {
    name: "마크",
    group: ["NCT", "NCT127", "NCT DREAM"],
    profileImage: "",
  },
  {
    name: "도영",
    group: ["NCT", "NCT127"],
    profileImage: "",
  },
  {
    name: "켄지",
    profileImage: "",
  },
  {
    name: "소희",
    group: ["원더걸스"],
    profileImage: "",
  },
  {
    name: "나비스",
    profileImage: "",
  },
  {
    name: "윈터",
    group: ["aespa"],
    profileImage: "",
  },
  {
    name: "수호",
    group: ["exo"],
    profileImage: "",
  },
  {
    name: "디오",
    group: ["exo"],
    profileImage: "",
  },
  {
    name: "수영",
    group: ["소녀시대"],
    profileImage: "",
  },
  {
    name: "태연",
    group: ["소녀시대"],
    profileImage: "",
  },
  {
    name: "동해",
    group: ["슈퍼주니어"],
    profileImage: "",
  },
  {
    name: "키",
    group: ["샤이니"],
    profileImage: "",
  },
  {
    name: "민호",
    group: ["샤이니"],
    profileImage: "",
  },
  {
    name: "조이",
    group: ["레드벨벳"],
    profileImage: "",
  },
  {
    name: "아이린",
    group: ["레드벨벳"],
    profileImage: "",
  },
  {
    name: "효연",
    group: ["소녀시대"],
    profileImage: "",
  },
  {
    name: "웬디",
    group: ["레드벨벳"],
    profileImage: "",
  },
  {
    name: "카리나",
    group: ["aespa"],
    profileImage: "",
  },
  {
    name: "지젤",
    group: ["aespa"],
    profileImage: "",
  },
  {
    name: "유리",
    group: ["소녀시대"],
    profileImage: "",
  },
  {
    name: "써니",
    group: ["소녀시대"],
    profileImage: "",
  },
];

export const MOCK_EVENTS: EventInfoType[] = [
  {
    placeName: "스타벅스이름이완전매우엄청길어요",
    eventType: "카페",
    groupId: "뉴진스",
    artists: ["민지"],
    startDate: "2024-01-29",
    endDate: "2024-01-30",
    address: "서울 중구 삼일대로 343",
    addressDetail: "",
    userId: "test-user",
    eventImages: ["https://thumb.mtstarnews.com/06/2023/09/2023090715013844673_1.jpg/dims/optimize"],
    description: "민지 생일 카페입니다~!",
    eventUrl: "https://newjeans2024.com",
    organizerSns: "minji_2024",
    snsType: "인스타그램",
    tags: ["굿즈", "엽서"],
  },
  {
    placeName: "투썸플레이스",
    eventType: "나눔",
    groupId: "뉴진스",
    artists: ["하니"],
    startDate: "2024-01-17",
    endDate: "2024-01-18",
    address: "서울특별시 강남구 와우산로 00-00 1층",
    addressDetail: "",
    userId: "test-user",
    eventImages: ["https://img.hankyung.com/photo/202305/03.33500801.1.jpg"],
    description: "민지 생일 카페입니다~!",
    eventUrl: "https://newjeans2024.com",
    organizerSns: "minji_2024",
    snsType: "인스타그램",
    tags: ["포토카드", "스티커", "컵홀더", "엽서", "굿즈", "티켓", "포스터", "기타"],
  },
  {
    placeName: "최승철 카페 카페 이름이 매우 길어요",
    eventType: "카페",
    groupId: "세븐틴",
    artists: ["최승철"],
    startDate: "2024-01-28",
    endDate: "2024-01-30",
    address: "서울특별시 마포구 와우산로 00-00 1층",
    addressDetail: "",
    userId: "test-user",
    eventImages: [
      "https://i.namu.wiki/i/cVUeYWpLEnOij4dYSX9dC12I4Ns552izzk0koy-fOnWs6T17-zbthepDB3d-8fvRLkqVpPB_fDx3x2vpXlw5zf-E3qGLEn3NzU6b6R4BjIK-I4ovu0xJlhTobjdAsuLzIAyGk52T7wYKQI0D32ZiyA.webp",
    ],
    description: "민지 생일 카페입니다~!",
    eventUrl: "https://newjeans2024.com",
    organizerSns: "minji_2024",
    snsType: "인스타그램",
    tags: ["컵홀더", "포토카드", "엽서", "스티커"],
  },
  {
    placeName: "윤정한 카페",
    eventType: "카페",
    groupId: "세븐틴",
    artists: ["윤정한"],
    startDate: "2024-01-28",
    endDate: "2024-01-30",
    address: "서울특별시 마포구 와우산로 00-00 1층",
    addressDetail: "",
    userId: "test-user",
    eventImages: [
      "https://i.namu.wiki/i/ih4PcJTM8PGahDKVMYEwEjrC0vMmddvSXpqRDXQTvZcCJV15TlntztbIHBY1F_nBDWcXUpolcAO5uqqhCtu32ZE_qNurPG9RTmBan8V02P0Bscv2FE7TwT6aufvY24G-r_Fsy1XxXQPBffXRwa5xaA.webp",
    ],
    description: "민지 생일 카페입니다~!",
    eventUrl: "https://newjeans2024.com",
    organizerSns: "minji_2024",
    snsType: "인스타그램",
    tags: ["컵홀더", "포토카드", "엽서", "스티커"],
  },
  {
    placeName: "홍지수 카페",
    eventType: "카페",
    groupId: "세븐틴",
    artists: ["홍지수"],
    startDate: "2024-01-28",
    endDate: "2024-01-30",
    address: "서울특별시 마포구 와우산로 00-00 1층",
    addressDetail: "",
    userId: "test-user",
    eventImages: [
      "https://i.namu.wiki/i/c5dTk5Q7fJffyTVjpS_pR5tKHkaO622VIGckO2UMSd_t-eSowqlardGCFh3VIXQo3zElqYk2Efi08MqulFX7UXWo_yiO6i5kE8g76Vvq4QCv7P1dVUgbIJZG3fhc6jaJsEf-kT7t-evs0C4C_FGChg.webp",
    ],
    description: "민지 생일 카페입니다~!",
    eventUrl: "https://newjeans2024.com",
    organizerSns: "minji_2024",
    snsType: "인스타그램",
    tags: ["컵홀더", "포토카드", "엽서", "스티커"],
  },
  {
    placeName: "문준휘 카페",
    eventType: "카페",
    groupId: "세븐틴",
    artists: ["문준휘"],
    startDate: "2024-01-28",
    endDate: "2024-01-30",
    address: "서울특별시 마포구 와우산로 00-00 1층",
    addressDetail: "",
    userId: "test-user",
    eventImages: [
      "https://i.namu.wiki/i/Up9Lcqxr67_7YCWAJ3K7nL7reiObQvNsneW9lVRcH9zJlAaB6_iBL40fNptbmo_MogjR-zbkoGPKs7E3Y1bsv0rBwRu7RvBuEHmNqu_8nKdXEyfAA6VaQmVMVfgE3Idyfkbsm6Rbj3LyJVoHiusNyA.webp",
    ],
    description: "민지 생일 카페입니다~!",
    eventUrl: "https://newjeans2024.com",
    organizerSns: "minji_2024",
    snsType: "인스타그램",
    tags: ["컵홀더", "포토카드", "엽서", "스티커"],
  },
  {
    placeName: "권순영 카페",
    eventType: "카페",
    groupId: "세븐틴",
    artists: ["권순영"],
    startDate: "2024-01-28",
    endDate: "2024-01-30",
    address: "서울특별시 마포구 와우산로 00-00 1층",
    addressDetail: "",
    userId: "test-user",
    eventImages: [
      "https://i.namu.wiki/i/q81B70Xx5hl4Ps0dULoQCHiqRHOCg9xeJaAlOKpNeytaQf5xaw4Qom7NS4FUbEX_SbcozM0UIO75jYTCXortVpsUbgtBLH9pXGJ8mvbH1KeMQP1LGweQfwR_chaN7fuPxA_Dr7hqG92-c7IU9b4s6w.webp",
    ],
    description: "민지 생일 카페입니다~!",
    eventUrl: "https://newjeans2024.com",
    organizerSns: "minji_2024",
    snsType: "인스타그램",
    tags: ["컵홀더", "포토카드", "엽서", "스티커"],
  },
  {
    placeName: "전원우 카페",
    eventType: "카페",
    groupId: "세븐틴",
    artists: ["전원우"],
    startDate: "2024-01-28",
    endDate: "2024-01-30",
    address: "서울특별시 마포구 와우산로 00-00 1층",
    addressDetail: "",
    userId: "test-user",
    eventImages: [
      "https://i.namu.wiki/i/mIBNitRZKRFMcIrrGj9kPaitPy6lKAsbAY3sTxv-WCs3SWpEexCOk4_LHPfC06YxUXruRJ4Oy_rI8QnqZdjxB2XHearzAG1CQbdiw0iIRCC67mzS-D85cTGBMV5mxnzswIWDtDvdT0gl-AYmLAFOeA.webp",
    ],
    description: "민지 생일 카페입니다~!",
    eventUrl: "https://newjeans2024.com",
    organizerSns: "minji_2024",
    snsType: "인스타그램",
    tags: ["컵홀더", "포토카드", "엽서", "스티커"],
  },
  {
    placeName: "이지훈 카페",
    eventType: "카페",
    groupId: "세븐틴",
    artists: ["이지훈"],
    startDate: "2024-01-28",
    endDate: "2024-01-30",
    address: "서울특별시 마포구 와우산로 00-00 1층",
    addressDetail: "",
    userId: "test-user",
    eventImages: [
      "https://i.namu.wiki/i/xqplchTSk2YQNSfiOeXSML0o16jhkSYO_SaPbA__YLoPkqf7m6LvK8SoKYMn92YsIUeyQotbsp8nF7L1tF19geA4YScHru91tbXEvFIZ0EFtL4GJ-HzEp9hoSlZy1THUAhYLS-fxMwH8EG53fjHy6Q.webp",
    ],
    description: "민지 생일 카페입니다~!",
    eventUrl: "https://newjeans2024.com",
    organizerSns: "minji_2024",
    snsType: "인스타그램",
    tags: ["컵홀더", "포토카드", "엽서", "스티커"],
  },
  {
    placeName: "서명호 카페",
    eventType: "카페",
    groupId: "세븐틴",
    artists: ["서명호"],
    startDate: "2024-01-28",
    endDate: "2024-01-30",
    address: "서울특별시 마포구 와우산로 00-00 1층",
    addressDetail: "",
    userId: "test-user",
    eventImages: [
      "https://i.namu.wiki/i/-DQNkooD8TmSLN4QKCN5XfZk5dLl7TTPTAZvF-Yz6bfADYU6Ftb9g89DsP1JwtRENSaeKHvjRxR3HJdwTpRTdfQybRohEE3MjHF77W1-to_SUeoKti1WQzwbtgP0l23sfI7E53670t7f8VXOVbAw6A.webp",
    ],
    description: "민지 생일 카페입니다~!",
    eventUrl: "https://newjeans2024.com",
    organizerSns: "minji_2024",
    snsType: "인스타그램",
    tags: ["컵홀더", "포토카드", "엽서", "스티커"],
  },
  {
    placeName: "김민규 카페",
    eventType: "카페",
    groupId: "세븐틴",
    artists: ["김민규"],
    startDate: "2024-01-28",
    endDate: "2024-01-30",
    address: "서울특별시 마포구 와우산로 00-00 1층",
    addressDetail: "",
    userId: "test-user",
    eventImages: [
      "https://i.namu.wiki/i/dgtlF-9k6OFGAMBPzDuCIXUtfLGEILClbkcuTljNpAI2z9sDGAHJlllddsHzEhnIzotHKYeFHBp7-3nD-iY9LlMq3K-04KfzDWyS0wmSO0BdeOV3vai1JQ4LqoNiziWdVK0-JcWh23jfpizrxtCldg.webp",
    ],
    description: "민지 생일 카페입니다~!",
    eventUrl: "https://newjeans2024.com",
    organizerSns: "minji_2024",
    snsType: "인스타그램",
    tags: ["컵홀더", "포토카드", "엽서", "스티커"],
  },
  {
    placeName: "이석민 카페",
    eventType: "카페",
    groupId: "세븐틴",
    artists: ["이석민"],
    startDate: "2024-01-28",
    endDate: "2024-01-30",
    address: "서울특별시 마포구 와우산로 00-00 1층",
    addressDetail: "",
    userId: "test-user",
    eventImages: [
      "https://i.namu.wiki/i/o2BCmdj_aZORmwm7THhsvmmu73F-amPFMcHShE-Ko-WtP1q50Qg5y3QZSwdUjILA-kQZS7xc7n8JUIwNWug7RhVtTZ5SmRAJpUITm_hbJrbr_pwu4ocTG9ZDcvnTaqff3phNSEwUsYgIkKaybVEhZw.webp",
    ],
    description: "민지 생일 카페입니다~!",
    eventUrl: "https://newjeans2024.com",
    organizerSns: "minji_2024",
    snsType: "인스타그램",
    tags: ["컵홀더", "포토카드", "엽서", "스티커"],
  },
  {
    placeName: "부승관 카페",
    eventType: "카페",
    groupId: "세븐틴",
    artists: ["부승관"],
    startDate: "2024-01-28",
    endDate: "2024-01-30",
    address: "서울특별시 마포구 와우산로 00-00 1층",
    addressDetail: "",
    userId: "test-user",
    eventImages: [
      "https://i.namu.wiki/i/xnMXHIEVbD9hczcvXAujBvOrlJ206dsAaLWGuxZyPJhJcG5AX4tJkusB6f_RdJwHYZJPvX3w_8lfnv-mkk1FcC2ONYtwKULNSVVZZs8VPG2hEtW5xCWF4hNcVLf-BKTF8fnWmsME3EzpKtfBnGarzQ.webp",
    ],
    description: "민지 생일 카페입니다~!",
    eventUrl: "https://newjeans2024.com",
    organizerSns: "minji_2024",
    snsType: "인스타그램",
    tags: ["컵홀더", "포토카드", "엽서", "스티커"],
  },
  {
    placeName: "최한솔 카페",
    eventType: "카페",
    groupId: "세븐틴",
    artists: ["최한솔"],
    startDate: "2024-01-28",
    endDate: "2024-01-30",
    address: "서울특별시 마포구 와우산로 00-00 1층",
    addressDetail: "",
    userId: "test-user",
    eventImages: [
      "https://i.namu.wiki/i/ydXRy-sRwT9oYNqkNav_mooSYtgjmyqCqWbXS0e1jaltpCRmrrpyKlKUfRJyabn0bXyt1g8L3ZG4Qp3NOp1u2Y2SMFxM3szqoG6lqm-IalUKaj8KD70UAsjNUPRsznq_iNy_U9WaSNcnqVlTgKMZwQ.webp",
    ],
    description: "민지 생일 카페입니다~!",
    eventUrl: "https://newjeans2024.com",
    organizerSns: "minji_2024",
    snsType: "인스타그램",
    tags: ["컵홀더", "포토카드", "엽서", "스티커"],
  },
  {
    placeName: "이찬 카페",
    eventType: "카페",
    groupId: "세븐틴",
    artists: ["이찬"],
    startDate: "2024-01-28",
    endDate: "2024-01-30",
    address: "서울특별시 마포구 와우산로 00-00 1층",
    addressDetail: "",
    userId: "test-user",
    eventImages: [
      "https://i.namu.wiki/i/Jlh9d_TSuVTU8oGNge67qcK08CtwsUaHDFCPzCFnUigDIvA2hIQbLxnyle2A5ZIDK6C7vKMtVDmDRTDmT5j9xnr_UXhw6ENoiSHccpEFNN3KNZZSRuIbM4TrgVcAThdIG1AqUtFbsLdXb1O0-W2gIw.webp",
    ],
    description: "민지 생일 카페입니다~!",
    eventUrl: "https://newjeans2024.com",
    organizerSns: "minji_2024",
    snsType: "인스타그램",
    tags: ["컵홀더", "포토카드", "엽서", "스티커"],
  },
];

export const MOCK_REVIEWS = [
  {
    userId: "test",
    eventId: "test",
    isPublic: true,
    rating: true,
    description: "메뉴도 진짜 맛있고 특전도 너무 예뻐요. KTX타고 3시간 걸려서 갔는데 후회 없습니다. 3일차 오후라서 포카 없을까봐 걱정했는데 다행히 수량 넉넉해서 다 받았어요.",
    reviewImages: [
      "https://thumb.mtstarnews.com/06/2023/09/2023090715013844673_1.jpg/dims/optimize",
      "https://thumb.mtstarnews.com/06/2023/09/2023090715013844673_1.jpg/dims/optimize",
      "https://thumb.mtstarnews.com/06/2023/09/2023090715013844673_1.jpg/dims/optimize",
      "https://thumb.mtstarnews.com/06/2023/09/2023090715013844673_1.jpg/dims/optimize",
      "https://thumb.mtstarnews.com/06/2023/09/2023090715013844673_1.jpg/dims/optimize",
      "https://thumb.mtstarnews.com/06/2023/09/2023090715013844673_1.jpg/dims/optimize",
      "https://thumb.mtstarnews.com/06/2023/09/2023090715013844673_1.jpg/dims/optimize",
    ],
    like: 1,
  },
  {
    userId: "test",
    eventId: "test",
    isPublic: false,
    rating: false,
    description: "사람 너무 많아요 특전 다나갔습니다 가실분들 참고",
    reviewImages: [
      "https://thumb.mtstarnews.com/06/2023/09/2023090715013844673_1.jpg/dims/optimize",
      "https://thumb.mtstarnews.com/06/2023/09/2023090715013844673_1.jpg/dims/optimize",
      "https://thumb.mtstarnews.com/06/2023/09/2023090715013844673_1.jpg/dims/optimize",
      "https://thumb.mtstarnews.com/06/2023/09/2023090715013844673_1.jpg/dims/optimize",
    ],
    like: 0,
  },
  {
    userId: "test",
    eventId: "test",
    isPublic: true,
    rating: true,
    description: "메뉴도 진짜 맛있고 특전도 너무 예뻐요. KTX타고 3시간 걸려서 갔는데 후회 없습니다. 3일차 오후라서 포카 없을까봐 걱정했는데 다행히 수량 넉넉해서 다 받았어요.",
    reviewImages: [
      "https://thumb.mtstarnews.com/06/2023/09/2023090715013844673_1.jpg/dims/optimize",
      "https://thumb.mtstarnews.com/06/2023/09/2023090715013844673_1.jpg/dims/optimize",
      "https://thumb.mtstarnews.com/06/2023/09/2023090715013844673_1.jpg/dims/optimize",
      "https://thumb.mtstarnews.com/06/2023/09/2023090715013844673_1.jpg/dims/optimize",
    ],
    like: 2,
  },

  {
    userId: "test",
    eventId: "test",
    public: false,
    rating: false,
    description: "사람 너무 많아요 특전 다나갔습니다 가실분들 참고",
    reviewImages: [
      "https://thumb.mtstarnews.com/06/2023/09/2023090715013844673_1.jpg/dims/optimize",
      "https://thumb.mtstarnews.com/06/2023/09/2023090715013844673_1.jpg/dims/optimize",
      "https://thumb.mtstarnews.com/06/2023/09/2023090715013844673_1.jpg/dims/optimize",
      "https://thumb.mtstarnews.com/06/2023/09/2023090715013844673_1.jpg/dims/optimize",
    ],
    like: 0,
  },
];
