export const EventMockData = [
  {
    placeName: "최승철 카페",
    artistName: "최승철",
    eventType: "생일카페",
    address: "마포구",
    date: "01.19 ~ 01.20",
  },
  {
    placeName: "윤정한 카페",
    artistName: "윤정한",
    eventType: "생일카페",
    address: "마포구",
    date: "01.19 ~ 01.20",
  },
  {
    placeName: "홍지수 카페",
    artistName: "홍지수",
    eventType: "생일카페",
    address: "마포구",
    date: "01.19 ~ 01.20",
  },
  {
    placeName: "문준휘 카페",
    artistName: "문준휘",
    eventType: "생일카페",
    address: "마포구",
    date: "01.19 ~ 01.20",
  },
  {
    placeName: "권순영 카페",
    artistName: "권순영",
    eventType: "생일카페",
    address: "마포구",
    date: "01.19 ~ 01.20",
  },
  {
    placeName: "전원우 카페",
    artistName: "전원우",
    eventType: "생일카페",
    address: "마포구",
    date: "01.19 ~ 01.20",
  },
  {
    placeName: "이지훈 카페",
    artistName: "이지훈",
    eventType: "생일카페",
    address: "마포구",
    date: "01.19 ~ 01.20",
  },
  {
    placeName: "서명호 카페",
    artistName: "서명호",
    eventType: "생일카페",
    address: "마포구",
    date: "01.19 ~ 01.20",
  },
  {
    placeName: "김민규 카페",
    artistName: "김민규",
    eventType: "생일카페",
    address: "마포구",
    date: "01.19 ~ 01.20",
  },
  {
    placeName: "이석민 카페",
    artistName: "이석민",
    eventType: "생일카페",
    address: "마포구",
    date: "01.19 ~ 01.20",
  },
  {
    placeName: "부승관 카페",
    artistName: "부승관",
    eventType: "생일카페",
    address: "마포구",
    date: "01.19 ~ 01.20",
  },
  {
    placeName: "최한솔 카페",
    artistName: "최한솔",
    eventType: "생일카페",
    address: "마포구",
    date: "01.19 ~ 01.20",
  },
  {
    placeName: "이찬 카페",
    artistName: "이찬",
    eventType: "생일카페",
    address: "마포구",
    date: "01.19 ~ 01.20",
  },
];
